title: Ian Secretario
email: iansecretario@guidem.ph
baseurl: '' 
github_username: iansecretario
remote_theme: "dracula/gh-pages"

highlighter: rouge
plugins:
  #- jekyll-seo-tag
  - jemoji
  
#theme: jekyll-theme-hacker
#show_header: "false"
