remote_theme: "dracula/gh-pages"

aplugins:
  #- jekyll-seo-tag
  
#theme: jekyll-theme-hacker
#show_header: "false"

markdown: kramdown
kramdown:
  syntax_highlighter: pygments
highlighter: pygments
