title: Offense is the best Defense
#email: iansecretario@guidem.ph
baseurl: '/'
#github_username: iansecretario
remote_theme: "dracula/gh-pages"
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-sitemap

#theme: jekyll-theme-hacker
show_header: "false"
#show_header: true
#enableTags: true

#social:
#    - icon: fa-twitter
#      link: "https://twitter.com/iansecretario"
#    - icon: fa-github
#      link: "https://github.com/iAnsecretario"#

#share:
#  twitter_username: iAnsecretario
