remote_theme: "dracula/gh-pages"

aplugins:
  #- jekyll-seo-tag
  
#theme: jekyll-theme-hacker
#show_header: "false"

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
    span:
      line_numbers: true
